name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check if the last commit was by GitHub Actions
      id: check_last_commit
      run: |
        git log -1 --pretty=format:'%an' > author.txt
        author=$(cat author.txt)
        if [ "$author" = "github-actions[bot]" ]; then
          echo "Commit made by GitHub Actions bot, skipping the workflow."
          exit 0
        fi

    - name: Read version
      id: read_version
      run: |
        version=$(cat version.txt)
        echo "::set-output name=version::$version"

    - name: Increment version
      id: increment_version
      run: |
        version=$(( $(cat version.txt) + 1 ))
        echo $version > version.txt
        echo "::set-output name=new_version::$version"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rick1sanchez3c7/rolscheduler:latest --tag rick1sanchez3c7/rolscheduler:2.0.${{ steps.increment_version.outputs.new_version }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push the Docker image
      run: |
        docker push rick1sanchez3c7/rolscheduler:latest
        docker push rick1sanchez3c7/rolscheduler:2.0.${{ steps.increment_version.outputs.new_version }}

    - name: Commit new version
      if: ${{ success() }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add version.txt
        git commit -m "Increment version to 2.0.${{ steps.increment_version.outputs.new_version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
