name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check if the last commit was by GitHub Actions
        id: check_last_commit
        run: |
          git log -1 --pretty=format:'%an' > author.txt
          author=$(cat author.txt)
          if [ "$author" = "github-actions[bot]" ]; then
            echo "Commit made by GitHub Actions bot, skipping the workflow."
            exit 0

      - name: Read version
        id: read_version
        run: |
          version=$(cat version.txt)
          echo "::set-output name=version::$version"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile --tag rick1sanchez3c7/rolscheduler:latest --tag rick1sanchez3c7/rolscheduler:${{ steps.read_version.outputs.version }} --push .
